# Use a lightweight OpenJDK base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the built JAR file into the container
# Assuming your build process creates a JAR in target/
COPY target/PNCService.jar app.jar

# Expose the port your Spring Boot application listens on
EXPOSE 9090

# Define the command to run the application when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
